### ISSUE TITLE
After attaching to eNB, UE doesn't access to the internet.

### ISSUE THREAD

**Issue by hyunseoha** [srsran/srsRAN#1000]
## Issue Description ##
After attaching to eNB, UE doesn't access to the internet. The connection  eNB & EPC looks good, but UE & eNB is not stable.

1. I try to add apn address on UE, but this is not saved on the smartphone. (OnePlus Nord CE 5G, Snapdragon 750G)
2. The connection between eNB and UE is on and off. Please see the uploaded logs. if you need more info, please tell me. I will give you the immediate response.

## Setup Details ##
I am using USRP B210 as eNB and OnePlus Nord CE 5G as UE.
I am actually doing with the Smartphone, so i am worried about the receiving power at USRP B210, so i have -20 dBm attenuation damper at the receiver signal. the Smartphone is in the blackbox, from there no LTE signal from my configuration coming out.

The SIM card is sysmoISIM-SJA2 and all the SIM data is uploaded in user_db.csv.

epc.conf and enb.conf would be uploaded.

i tried many other configuration, but n_prb = 15 && dl_earfcn = 1934 is working with the smartphone.

The Smartphone gets the signal and it shows that it has a roaming signal, but no data symbol, such as LTE or 3G, showing.

If you have more ideas about nPRB and dlEARFCN, please give me more details. It would be helpful.

Helpful criticism is always welcomed.

## Expected Behavior ##
UE (OnePlus Nord CE 5G) is not disconnected from eNB, and it can access to Internet.

## Actual Behaviour ##
no internet (offline) on the smartphone and disconnection rnti=0x47 shown.

## Steps to reproduce the problem ##
[srs_doc.zip](https://github.com/srsran/srsRAN/files/9645683/srs_doc.zip)
Log and conf are together uploaded.

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
Probably something wrong with forwarding of user/internet traffic make sure you follow the COTS phone app-note and pay attention to the network config, i.e. https://docs.srsran.com/en/latest/app_notes/source/cots_ue/source/index.html#run-masquerading-script
