### ISSUE TITLE
Can I make a voLTE call with the LTE network？

### ISSUE THREAD

**Issue by SpongeBobaa** [srsran/srsRAN#1005]
I‘ve already connected to my LTE station. I test it but I can't make a voLTE call with others.

Do I lose something in my station setup?

**Comment by jtang613** [comment]
A VoLTE call will require an IMS and a more feature-rich EPC than the basic EPC included with SRSRAN. I recommend taking a look at the Open5gs project and their excellent documentation. They have some tutorials that cover this topic.

**Comment by andrepuschmann** [comment]
Thanks again @jtang613 for helping out.
