### ISSUE TITLE
srsRAN zmq registration failed due to adding 0 at the end of configured IMSI 

### ISSUE THREAD

**Issue by Lily-Ats** [srsran/srsRAN#1015]
Dear team,

thank you for the great work. I am facing issue for srsRAN zmp.
Configure different IMSI in ue.conf other than the example configure file. when try 5G SA registration, UE sends 16 digit number of IMSI by adding 0 in the end of configured IMSI. so got registration failed with PLMN not allowed. But works great with example configured IMSI.

thanks,
Lily

**Comment by andrepuschmann** [comment]
Thanks for the report. It could well be that there is an issue with certain IMSI lengths - but we can't confirm it without a proper test. I'd close the ticket, unless you want to look into it yourself, as we don't have the resources to look into it ourselves.
