### ISSUE TITLE
couldnot start enb

### ISSUE THREAD

**Issue by shankar5gresearch** [srsran/srsRAN#1019]
## Issue Description ##
[installed srsRAN with ZMQ VIRTUAL RADIO but couldnot run enb.conf ]

## error Details ##
We are tried running the enb start cmb from build folder but getting errors as follows;
couldn't open enb.config, trying /home/root/.config/srsRAN/enb.config
couldn't open sib.conf......
couldn't open rr.conf
couldn't open rb.conf............

**Comment by qiqingh** [comment]
Also confronted with the same problem here.

**Comment by qiqingh** [comment]
Solved
Missing the step to install the built srsRAN, which makes it couldn't find the configuration file.
