### ISSUE TITLE
Problem with SRSRAN and the timestamp solution

### ISSUE THREAD

**Issue by LunaWuna** [srsran/srsRAN#1053]
## Issue Description ##
Starting up a eNB on a plutosdr (the "pluto plus" "enhanced" version) brings up ``Error reading rx ringbuffer. Invalid header``

## Setup Details ##
Linux mint with a "pluto plus" SDR running the timestamp solution, the TXRX test works.

## Expected Behavior ##
eNB to start and a signal to be transmitted

## Actual Behaviour ##
![image](https://user-images.githubusercontent.com/117489177/206092749-3b40890f-6c5c-4c78-b4b1-51578501e8dc.png)
This happens on both a linux mint VM and another PC running ubuntu on bare metal.

**Comment by ofontbach** [comment]
A fix has been pushed in the timestamp repository. Please, update your local one and try again. Also, in case it is necessary, open a new issue in the timestamp repository (https://github.com/srsran/zynq_timestamping) not here. Thanks.

**Comment by andrepuschmann** [comment]
Closing this issue as fixed. As mentioned by @ofontbach please use the timestamping repo in case there is anything else with it.
