### ISSUE TITLE
The latest version (22.10) package isn't available Ubuntu

### ISSUE THREAD

**Issue by iman432** [srsran/srsRAN#1058]
The latest version (22.10) package isn't available on Ubuntu and available version is 22.04.1 in repository. there is plan for update package?

![Capture](https://user-images.githubusercontent.com/44318450/207839992-15445da9-0935-4ae3-bfc3-0065ad579214.PNG)

**Comment by andrepuschmann** [comment]
Yes, sorry, we'll update the repo shortly.

**Comment by iman432** [comment]
Thanks a lot.
