### ISSUE TITLE
dynamic MCS adaptation

### ISSUE THREAD

**Issue by aabedii** [srsran/srsRAN#1065]
## Issue Description ##
[Describe the issue in detail]
Missing dynamic MCS adaptation for NR

## Setup Details ##
5G SA or NSA

## Expected Behavior ##
MCS changes dynamically as the channel changes

## Actual Behaviour ##
No support. MCS is fixed.

## Steps to reproduce the problem ##
Missing feature.

## Additional Information ##
Is there any plan to add this feature soon? If not, could you please refer me to how one can add this functionality in the code? Specifically, where in the code I can implement this feature.

**Comment by andrepuschmann** [comment]
We will release a complete new gNB stack early next year which will support dynamic MCS selection. The gNB in the current srsRAN repo will not get this feature backported.

**Comment by teo-tsou** [comment]
Is this release already out? Also if I want to develop such functionality in the srsLTE, could you please suggest me which file should I modify on the source code? Thank you!

**Comment by ismagom** [comment]
Hi @teo-tsou,

Yes the new release is here: https://github.com/srsran/srsRAN_Project

**Comment by teo-tsou** [comment]
Thank you very much for your reply. Still can't find out how to change mcs dynamically, is there any doc? Can you please please help me on reaching to the cqi/mcs lookup table?

**Comment by frankist** [comment]
You can find the files `mcs_calculator.h` / `mcs_calculator.cpp` in the `lib/scheduler/support` directory.
