### ISSUE TITLE
cannot enable debug mode

### ISSUE THREAD

**Issue by ridzafauzi** [srsran/srsRAN#1077]
## Issue Description ##
cannot enable debug mode

## Setup Details ##
git clone https://github.com/srsRAN/srsRAN.git
cd srsRAN
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../
make
make test
sudo srsue

## Expected Behavior ##
log file containing debug info in srsran_backtrace.log

## Actual Behaviour ##
srsran_backtrace.log cannot be found

or am i am missing any steps?

**Comment by andrepuschmann** [comment]
hey, the backtrace is only generated if the app crashes. The UE generates a log in `/tmp/srsue.log`. Hope that helps.

**Comment by ridzafauzi** [comment]
got it! thanks
