### ISSUE TITLE
Does not work with Bladerf 2.0 micro

### ISSUE THREAD

**Issue by pricalinat** [srsran/srsRAN#1101]
## Issue Description ##
I tried to use Bladerf 2.0 micro to connect, but found that it was stuck when running.
## Setup Details ##
![image](https://user-images.githubusercontent.com/52783243/219855513-56dd43a2-ca32-494d-9444-6f3f025dafab.png)

![image](https://user-images.githubusercontent.com/52783243/219855544-86779dbe-c9b8-48ee-ac8b-35315a50db79.png)

![image](https://user-images.githubusercontent.com/52783243/219855595-dc523fb1-2a3d-4e47-bc70-3434f6980e12.png)

![image](https://user-images.githubusercontent.com/52783243/219855649-dc6b1e66-ba98-4f24-9177-6297b5cbd192.png)

use default conf (sample)

![image](https://user-images.githubusercontent.com/52783243/219855717-b035c3cb-b688-440f-8cad-496b09fa7a56.png)
![image](https://user-images.githubusercontent.com/52783243/219855734-5160d969-0499-4fda-95a9-e089b5ba9671.png)
(And my phone doesn't have any signal, I don't know if it has something to do with it)

srsRAN version:latest

## Expected Behavior ##
I want it to work like zmq...

## Actual Behaviour ##
stuck for a long time

**Comment by pricalinat** [comment]
I follow this https://docs.srsran.com/en/latest/app_notes/source/cots_ue/source/index.html#introduction
when doing "Under the Network Operators find the network which you have just instantiated using srsRAN"
I can not find my srsran network

**Comment by gustavobsch** [comment]
hi @pricalinat , did you resolve this issue? also, may I ask about the  SIM card write program? where did you get the new 4.4.3 version from? thanks!
