### ISSUE TITLE
Supporting E-RabReleaseCommand after VoLTE call termination

### ISSUE THREAD

**Issue by demirten** [srsran/srsRAN#508]
I'm using srsLTE for testing purposes, integrated with an EPC and most of the things running quite well including VoLTE and ViLTE sessions and dedicated bearer setup.

But, when an INVITE session ends, we're sending Session-Termination diameter request to PCRF and it triggers MME to send E-RABReleaseCommand to eNb and it couldn't get any answer from srsenb.

I saw that ASN.1 message encode/decode process already done for the E-RABReleaseCommand in srsenb but it is not processing the received E-RABReleaseCommand.

Attached capture includes all of the s1ap, sip and diameter message flows from registration to end of the INVITE dialog. Packet no 141 is the E-RABReleaseCommand sent to the srsLTE. It will be good to support E-RABReleaseCommand to make MME's happy and allow continuous INVITE tests.

[erab-release-command.pcap.gz](https://github.com/srsLTE/srsLTE/files/4821100/erab-release-command.pcap.gz)

**Comment by andrepuschmann** [comment]
This isssue should be fixed with the new release. Please try it out again and reopen if it still exists.
