### ISSUE TITLE
srsue TDD can not connect to TDD network

### ISSUE THREAD

**Issue by apple68** [srsran/srsRAN#634]
## Issue Description ##
srsue TDD can not connect to TDD network

## Actual Behaviour ##
![image](https://user-images.githubusercontent.com/55984685/111430050-cbab9180-8734-11eb-88ec-63e539278a5f.png)
after ue send attach request, it will receive rrcconnect release!!!

**Comment by EugeneBogush** [comment]
hi,
which equipment you using?
would you to attach the logs and pcap-file?

**Comment by apple68** [comment]
> hi,
> which equipment you using?
> would you to attach the logs and pcap-file?

hello, I use usrpB210.Here are my logs and pcap-file.thank you!!!
[log.zip](https://github.com/srsLTE/srsLTE/files/6322002/log.zip)

**Comment by andrepuschmann** [comment]
Logs look pretty ok for the DL. Signal is not great but good enough. I'd say it's a UL issue. The ConnectionSetupComplete isn't going through. Check the antenna, cabling, power, etc.

**Comment by apple68** [comment]
> Logs look pretty ok for the DL. Signal is not great but good enough. I'd say it's a UL issue. The ConnectionSetupComplete isn't going through. Check the antenna, cabling, power, etc.

Wow!!! 
Hi, if srsue run in TDD mode, need special equipment or configuration?
Thank you!!!
I have tried various releases, only release_19.06 can attach TDD network.

**Comment by andrepuschmann** [comment]
I could well be that the particular config that the network uses only works with `release_19.06` then. We don't test all configs I am afraid.
