### ISSUE TITLE
srsUE failed to connect to srsENB 

### ISSUE THREAD

**Issue by olawhk** [srsran/srsRAN#656]
## Issue Description ##
Unable to connect UE with eNB 

## Setup Details ##
I'm running srsUE and srsUE on the same docker container and using zmq for fake RF.  Upon starting eNB which is successfully connected to an external EPC (Open5GS on a different container), I wasn't able to connect the UE to the eNB
It seems the process failed at RRC stage 

Any help/guidance on this would be greatly appreciate!  

Using commit c95020990 

## Expected Behavior ##
UE and eNB able to connect 

## Actual Behaviour ##
[What happens instead e.g. error message]

ue.log 

root@srslte-cd9584fc6-qmddx:/srsLTE/build/srsue/src# sudo ./srsue ue.conf
Reading configuration file ue.conf...

Built in Release mode using commit c95020990 on branch master.

Opening 1 channels in RF device=zmq with args="tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6"
CHx base_srate=23.04e6"
CHx id=ue
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
CH0 rx_port=tcp://localhost:2000
CH0 tx_port=tcp://*:2001
Warning: Failed to create thread with real-time priority. Creating it with normal priority: No such file or directory
Waiting PHY to initialize ...

Warning: Failed to create thread with real-time priority. Creating it with normal priority: Success
done!
Attaching UE...
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=-0.2 KHz
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Found PLMN:  Id=51501, TAC=1
Random Access Transmission: seq=46, tti=181, ra-rnti=0x2
RRC Connected
Random Access Complete.     c-rnti=0x46, ta=0
Attach failed (attempt 1/5)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=-0.2 KHz
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Found PLMN:  Id=51501, TAC=1
Received RRC Connection Release (releaseCause: other)
RRC IDLE
Attach failed (attempt 2/5)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=-0.2 KHz
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Found PLMN:  Id=51501, TAC=1
Random Access Transmission: seq=18, tti=9301, ra-rnti=0x2
RRC Connected
Random Access Complete.     c-rnti=0x47, ta=0
Attach failed (attempt 3/5)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=-0.2 KHz
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Found PLMN:  Id=51501, TAC=1
Received RRC Connection Release (releaseCause: other)
RRC IDLE
Attach failed (attempt 4/5)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=-0.2 KHz
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
Found PLMN:  Id=51501, TAC=1
Random Access Transmission: seq=42, tti=8501, ra-rnti=0x2
RRC Connected
Random Access Complete.     c-rnti=0x48, ta=0
Attach failed (attempt 5/5)
Received RRC Connection Release (releaseCause: other)
RRC IDLE

enb.log 

root@srslte-cd9584fc6-qmddx:/# tail -100 /tmp/enb.log 
    0000: 00 0b 40 32 00 00 03 00 00 00 02 00 05 00 08 00
    0010: 02 00 01 00 1a 00 1f 1e 37 7f c7 21 88 00 07 5d
05:46:56.804207 [S1AP   ] [I] Received RRC SDU
    0000: 47 70 6c d2 e8 00 07 5e 23 09 33 35 94 00 96 78
    0010: 33 52 f3
05:46:56.804231 [S1AP   ] [I] Tx S1AP SDU, UplinkNASTransport, rnti=0x46
    0000: 00 0d 40 3d 00 00 05 00 00 00 02 00 05 00 08 00
    0010: 02 00 01 00 1a 00 14 13 47 70 6c d2 e8 00 07 5e
05:47:06.047945 [S1AP   ] [I] Received RRC SDU
    0000: 07 41 71 08 59 51 10 10 00 00 11 11 07 f0 70 00
    0010: 00 00 00 10 00 04 02 01 d0 11 6f 04 f0 00 70 00
05:47:06.047970 [S1AP   ] [I] Tx S1AP SDU, UplinkNASTransport, rnti=0x46
    0000: 00 0d 40 4a 00 00 05 00 00 00 02 00 05 00 08 00
    0010: 02 00 01 00 1a 00 21 20 07 41 71 08 59 51 10 10
05:47:07.998457 [S1AP   ] [I] User inactivity - RNTI:0x46
05:47:07.998476 [S1AP   ] [I] Tx S1AP SDU, UEContextReleaseRequest, rnti=0x46
    0000: 00 12 40 15 00 00 03 00 00 00 02 00 05 00 08 00
    0010: 02 00 01 00 02 40 02 02 80
05:47:07.999338 [S1AP   ] [I] Rx S1AP SDU - UEContextReleaseCommand
    0000: 00 17 00 10 00 00 02 00 63 00 04 00 05 00 01 00
    0010: 02 40 01 20
05:47:07.999358 [S1AP   ] [I] Tx S1AP SDU, UEContextReleaseComplete, rnti=0x46
    0000: 20 17 00 0f 00 00 02 00 00 40 02 00 05 00 08 40
    0010: 02 00 01
05:47:07.999393 [S1AP   ] [I] UE context for RNTI:0x46 released
05:47:15.266152 [S1AP   ] [I] Tx S1AP SDU, InitialUEMessage, rnti=0x47
    0000: 00 0c 40 49 00 00 05 00 08 00 02 00 02 00 1a 00
    0010: 21 20 07 41 71 08 59 51 10 10 00 00 11 11 07 f0
05:47:15.275460 [S1AP   ] [I] Rx S1AP SDU - DownlinkNASTransport
    0000: 00 0b 40 38 00 00 03 00 00 00 02 00 06 00 08 00
    0010: 02 00 02 00 1a 00 25 24 07 52 00 5b 58 98 fb 06
05:47:15.288955 [S1AP   ] [I] Received RRC SDU
    0000: 07 53 08 6b ae 0d 60 9c 4f 65 c3
05:47:15.288979 [S1AP   ] [I] Tx S1AP SDU, UplinkNASTransport, rnti=0x47
    0000: 00 0d 40 35 00 00 05 00 00 00 02 00 06 00 08 00
    0010: 02 00 02 00 1a 00 0c 0b 07 53 08 6b ae 0d 60 9c
05:47:15.295949 [S1AP   ] [I] Rx S1AP SDU - DownlinkNASTransport
    0000: 00 0b 40 32 00 00 03 00 00 00 02 00 06 00 08 00
    0010: 02 00 02 00 1a 00 1f 1e 37 da 9e 14 ef 00 07 5d
05:47:15.311457 [S1AP   ] [I] Received RRC SDU
    0000: 47 52 58 3e 13 00 07 5e 23 09 33 35 94 00 96 78
    0010: 33 52 f3
05:47:15.311481 [S1AP   ] [I] Tx S1AP SDU, UplinkNASTransport, rnti=0x47
    0000: 00 0d 40 3d 00 00 05 00 00 00 02 00 06 00 08 00
    0010: 02 00 02 00 1a 00 14 13 47 52 58 3e 13 00 07 5e
05:47:24.688977 [S1AP   ] [I] Received RRC SDU
    0000: 07 41 71 08 59 51 10 10 00 00 11 11 07 f0 70 00
    0010: 00 00 00 10 00 04 02 01 d0 11 6f 04 f0 00 70 00
05:47:24.689000 [S1AP   ] [I] Tx S1AP SDU, UplinkNASTransport, rnti=0x47
    0000: 00 0d 40 4a 00 00 05 00 00 00 02 00 06 00 08 00
    0010: 02 00 02 00 1a 00 21 20 07 41 71 08 59 51 10 10
05:47:26.527019 [S1AP   ] [I] User inactivity - RNTI:0x47
05:47:26.527037 [S1AP   ] [I] Tx S1AP SDU, UEContextReleaseRequest, rnti=0x47
    0000: 00 12 40 15 00 00 03 00 00 00 02 00 06 00 08 00
    0010: 02 00 02 00 02 40 02 02 80
05:47:26.527940 [S1AP   ] [I] Rx S1AP SDU - UEContextReleaseCommand
    0000: 00 17 00 10 00 00 02 00 63 00 04 00 06 00 02 00
    0010: 02 40 01 20
05:47:26.527960 [S1AP   ] [I] Tx S1AP SDU, UEContextReleaseComplete, rnti=0x47
    0000: 20 17 00 0f 00 00 02 00 00 40 02 00 06 00 08 40
    0010: 02 00 02
05:47:26.527995 [S1AP   ] [I] UE context for RNTI:0x47 released
05:47:33.881538 [S1AP   ] [I] Tx S1AP SDU, InitialUEMessage, rnti=0x48
    0000: 00 0c 40 49 00 00 05 00 08 00 02 00 03 00 1a 00
    0010: 21 20 07 41 71 08 59 51 10 10 00 00 11 11 07 f0
05:47:33.891453 [S1AP   ] [I] Rx S1AP SDU - DownlinkNASTransport
    0000: 00 0b 40 38 00 00 03 00 00 00 02 00 07 00 08 00
    0010: 02 00 03 00 1a 00 25 24 07 52 00 4c 51 41 f9 95
05:47:33.904160 [S1AP   ] [I] Received RRC SDU
    0000: 07 53 08 b7 70 75 27 2c 63 d9 a3
05:47:33.904185 [S1AP   ] [I] Tx S1AP SDU, UplinkNASTransport, rnti=0x48
    0000: 00 0d 40 35 00 00 05 00 00 00 02 00 07 00 08 00
    0010: 02 00 03 00 1a 00 0c 0b 07 53 08 b7 70 75 27 2c
05:47:33.905047 [S1AP   ] [I] Rx S1AP SDU - DownlinkNASTransport
    0000: 00 0b 40 32 00 00 03 00 00 00 02 00 07 00 08 00
    0010: 02 00 03 00 1a 00 1f 1e 37 96 ec f2 8e 00 07 5d
05:47:33.919186 [S1AP   ] [I] Received RRC SDU
    0000: 47 64 8a cd 5b 00 07 5e 23 09 33 35 94 00 96 78
    0010: 33 52 f3
05:47:33.919207 [S1AP   ] [I] Tx S1AP SDU, UplinkNASTransport, rnti=0x48
    0000: 00 0d 40 3d 00 00 05 00 00 00 02 00 07 00 08 00
    0010: 02 00 03 00 1a 00 14 13 47 64 8a cd 5b 00 07 5e
05:47:45.168099 [S1AP   ] [I] User inactivity - RNTI:0x48
05:47:45.168119 [S1AP   ] [I] Tx S1AP SDU, UEContextReleaseRequest, rnti=0x48
    0000: 00 12 40 15 00 00 03 00 00 00 02 00 07 00 08 00
    0010: 02 00 03 00 02 40 02 02 80
05:47:45.168927 [S1AP   ] [I] Rx S1AP SDU - UEContextReleaseCommand
    0000: 00 17 00 10 00 00 02 00 63 00 04 00 07 00 03 00
    0010: 02 40 01 20
05:47:45.168944 [S1AP   ] [I] Tx S1AP SDU, UEContextReleaseComplete, rnti=0x48
    0000: 20 17 00 0f 00 00 02 00 00 40 02 00 07 00 08 40
    0010: 02 00 03
05:47:45.168975 [S1AP   ] [I] UE context for RNTI:0x48 released
05:51:59.005142 [S1AP   ] [I] Tx S1AP SDU, InitialUEMessage, rnti=0x49
    0000: 00 0c 40 49 00 00 05 00 08 00 02 00 04 00 1a 00
    0010: 21 20 07 41 71 08 59 51 10 10 00 00 11 11 07 f0
05:52:08.397279 [S1AP   ] [I] Received RRC SDU
    0000: 07 41 71 08 59 51 10 10 00 00 11 11 07 f0 70 00
    0010: 00 00 00 10 00 04 02 01 d0 11 6f 04 f0 00 70 00

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
Hey, please send EPC logs and pcap. It seems a signaling issue on the core side. Thanks

**Comment by andrepuschmann** [comment]
Closing this due to user inactivity for two weeks.

**Comment by jestrada2006** [comment]
This is probably due to RRC Inactivity timer.  I had a similar issue and it resolved it.

**Comment by sundepo** [comment]
> This is probably due to RRC Inactivity timer. I had a similar issue and it resolved it.

jestrada2006, how did you solve the problem?

**Comment by jestrada2006** [comment]
> 

It is located in enb.conf, near the bottom, in the advanced settings section.
