### ISSUE TITLE
when i running a 4G End-to-end System, Tx while waiting for EOB, timed out... 

### ISSUE THREAD

**Issue by shuimoshusheng** [srsran/srsRAN#669]
On machine 1 , my system is ubuntu 18.04.3,linux kernal is 5.4.0-73-generic, usrp is b210. the output:
![image](https://user-images.githubusercontent.com/15867686/118234667-3e7f8180-b4c6-11eb-81ea-dd1825712863.png)

On machine 2 , my system is ubuntu 18.04.3,linux kernal is 5.0.0-23-genericc, usrp is x310. the output:
![image](https://user-images.githubusercontent.com/15867686/118234740-5d7e1380-b4c6-11eb-8fb2-ca9ce812d733.png)

**Comment by andrepuschmann** [comment]
See comment in https://github.com/srsran/srsRAN/issues/667  I am closing this issue and expect you to provide a clear description in the other.
