### ISSUE TITLE
srsRAN 21.04 may have a bug if use usim in pcsc mode 

### ISSUE THREAD

**Issue by apple68** [srsran/srsRAN#674]
I use srsran21.04 in 4G mode, it works well if usim.mode=soft, but it does not work if usim.mode=pcsc.
usim.mode=pcsc
![Screenshot from 2021-05-26 13-01-21](https://user-images.githubusercontent.com/55984685/119605297-1deaec00-be23-11eb-8f84-97a4b3c9425a.png)
usim.mode=soft
![Screenshot from 2021-05-26 13-05-07](https://user-images.githubusercontent.com/55984685/119605358-3bb85100-be23-11eb-995d-ea15a910eddf.png)
Here is log file in mode pcsc.
[ue.log](https://github.com/srsran/srsRAN/files/6543947/ue.log)

**Comment by andrepuschmann** [comment]
I suggest you try again and check your setup. The external SIM support works for others just fine.
