### ISSUE TITLE
Cannot add PPA: 'ppa:~srsran/ubuntu/releases'.

### ISSUE THREAD

**Issue by vikramkapoor** [srsran/srsRAN#680]
## Issue Description ##
$ sudo add-apt-repository ppa:srsran/releases
Cannot add PPA: 'ppa:~srsran/ubuntu/releases'.
ERROR: '~srsran' user or team does not exist.
## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by vikramkapoor** [comment]
What works is sudo add-apt-repository ppa:softwareradiosystems/srsran

**Comment by suttonpd** [comment]
Where did you find instructions to use ppa:srsran/releases?

**Comment by vikramkapoor** [comment]
They were here
Installation Guide — srsRAN 21.04 documentation


| 
| 
|  | 
Installation Guide — srsRAN 21.04 documentation


 |

 |

 |




    On Monday, June 14, 2021, 07:52:02 AM PDT, Paul Sutton ***@***.***> wrote:  
 
 


Where did you find instructions to use ppa:srsran/releases?

**Comment by suttonpd** [comment]
Thanks - should be corrected now.
