### ISSUE TITLE
Correspondence between "tx_gain" in ue.conf and "set gain" in bladeRF

### ISSUE THREAD

**Issue by GodRadioMagic** [srsran/srsRAN#697]
## Issue Description ##
There are no description in ue.conf about Correspondence between "tx_gain" in ue.conf and "set gain" in bladeRF.

In case of bladeRFxA4, the range of tx gain is [-23.75  ~ 66]. And in case of bladeRFX40, it is [17 ~ 73].

Does the value of "tx_gain" in ue.conf correspond to the gain setting of bladeRF , or not ?

### [ue] ###

Ubunt18.04LTS
bladeRFxA4
BladeRF-cli = 1.8.0
BladeRF-lib = 2.4.0
BladeRF-fw = 2.4.0
BladeRF-fpga= 0.12.0
srsLTE_20_10_1

### [enb,epc] ###

Ubunt18.04LTS
USRPb210
srsLTE_20_10_1

## Actual Behaviour ##
Bellow is the tx spectrum of ue (bladeRFxA4). In ue.conf , tx_gain is set to 100,120,80,60,140,300.
In case of tx=60 is Green Spectrum.
In case of tx=100,120,80,60,140,300, these spectrums are almost the same power, so it seems that the max value of tx_gain is 80.
However,  power of these spectrums seem to be extremely lower than that of bladeRF Max tx power (+8dBm). 
(Since the signal from the tx channel of bladeRF is distributed 4 ways, the actual power should be about 6dB higher than the graph.)

![UE_spectrum(tx_gain=100,120,80,60,140,300)](https://user-images.githubusercontent.com/87161214/125216190-59b91280-e2f8-11eb-90b1-bd40833aa333.GIF)

## Steps to reproduce the problem ##
[enb,epc hostPC]
wifi turn-on , connect to the Internet
```
cd ~/srsLTE-release_20_10_1
sudo srsepc_if_masq.sh wlp6s0
```
[epc]
```
cd ~/srsLTE-release_20_10_1/srsepc
sudo srsepc epc.conf
```
[enb]
```
cd ~/srsLTE-release_20_10_1/srsenb
sudo srsenb enb.conf
```
[ue]
```
cd ~/srsLTE-release_20_10_1/srsue
sudo srsue ue.conf
```

**Comment by andrepuschmann** [comment]
Hey,

the `tx_gain` set in the config files is directly fed into the RF driver, be it UHD, Soapy or the native bladeRF driver. I am pretty sure that the max value is capped in all drivers, so what you're seeing is perfectly fine.

The max output power of the device is usually not achieved over such a wide bandwidth, i.e. 10 MHz in your case.

Hope that helps.
