### ISSUE TITLE
How to obtain/assing the number on a UE 

### ISSUE THREAD

**Issue by Kernelalive** [srsran/srsRAN#749]
## Issue Description ##
Hello!
I try to connect 2 UEs (google pixel 4) to SRS LTE in order to observe the communication (either text or call) among them through wireshark.So my question is if it is  possible to obtain or assign (if possible) a phone number for a UE that is registered on the mme.
## Setup Details ##
My set up is comprised by a NUC running  srsLTE attached with a USRP B210 and 2 UE (google pixel 4)
## Expected Behavior ##
[What you expect to happen]
I would like to investigate if  i  can obtain sensitive information between two UEs that are sending to each other  (through Wireshark)
## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
You can't assign a phone number to a phone. LTE only provides data services. Have a look at VoLTE and IMS installations, etc on how to do voice calls over LTE.
