### ISSUE TITLE
COTS UE clarification around PAP/CHAP NAS Authentication

### ISSUE THREAD

**Issue by knbchse** [srsran/srsRAN#753]
## Issue Description ##
[Describe the issue in detail]
I keep getting the error of 'Unhandled NAS integrity protected message LIBLTE_MME_MSG_TYPE_UPLINK_NAS_TRANSPORT' when running srsRAN.

I saw [here](https://docs.srsran.com/en/latest/usermanuals/source/srsepc/source/3_epc_trouble.html) that PAP/CHAP NAS authentication is not supported. I am using an iPhone 6s (A1688) and using Apple Configurator 2 to configure the cellular APN and authentication type. In Configurator 2, there is only the option between PAP and CHAP, there is no 'None' option. 

I am only assuming that the error message occurs due to this mismatch.

Is this authentication support in the development pipeline?

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

UE: iPhone 6s (A1688)

RAN: bladeRF xA4

EPC running on workstation:
AMD Ryzen 3700X (8C 16T)
32GB RAM

## Expected Behavior ##
[What you expect to happen]
No unhandled NAS messages

## Actual Behaviour ##
[What happens instead e.g. error message]
Unhandled NAS messages

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]
Run srsRAN with COTS iPhone and standard APN settings.

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
The phone you're using probably has further APNs configured and sends requests to establish sessions for those. srsEPC doesn't support mutliple APNs and leaves those requests unanswered. You can confirm this by checking the PCAP of the eNB.
But we are not planning to extend the EPC at this stage. I am closing the issue therefore.
