### ISSUE TITLE
srsue and srsenb doesn't read device args from ue.conf and enb.conf by ZeroMQ

### ISSUE THREAD

**Issue by emadrezz** [srsran/srsRAN#754]
## Issue Description ##
Hi , i was trying to simulate **Intra-eNB & S1 Handover** from sraRAN
I changed the device args and every thing the tutorial said about the device name and other stuff in the directory   _/root/.config/srsran/_ 
for example for enb I wrote like this:
`[rf]
#dl_earfcn = 3350
tx_gain = 80
rx_gain = 40
device_name = zmq
device_args = fail_on_disconnect=true,id=enb,tx_port0=tcp://*:2101,tx_port1=tcp://*:2201,rx_port0=tcp://localhost:2100,rx_port1=tcp://localhost:2200,id=enb,base_srate=23.04e6
`
as it clearly mentioned if srsenb reads the args we should have two channels , but when i run the code there is no such a thing.
I have just one channel, but not only this arg doesn't work the other args i set as  [https://docs.srsran.com/en/latest/app_notes/source/handover/source/index.html](url) said doesnt work.
srsenb:
`Opening 1 channels in RF device=zmq with args=fail_on_disconnect=true,id=enb,tx_port0=tcp://*:2101,tx_port1=tcp://*:2201,rx_port0=tcp://localhost:2100,rx_port1=tcp://localhost:2200,id=enb,base_srate=23.04e6
CHx base_srate=23.04e6
`
i can ignore this but in the resume when i run the srsue the ue does not attach im so confused i know there is smth wrong but i can't help it.

## Setup Details ##
I'm using ubuntu 20.04.3 LTS and by ZeroMQ device.
## Expected Behavior ##
[I expected what the srsRAN told happen, because all the terms are set as the tutorial said and the network connects when i use the original configure files (attaching UE as i mentioned) ]
## Actual Behavior ##
[i think the only problem here is that the args doesnt read from the configuration because the enb for example says:
`Reading configuration file /root/.config/srsran/enb.conf...
` 
but i see no action
]

![Screenshot from 2021-11-07 19-05-25](https://user-images.githubusercontent.com/88979187/140651567-c5050aa2-fcd8-43d4-a125-cc1277f91912.png)

**Comment by andrepuschmann** [comment]
Hey, I am not sure how your configs file look like because you don't share them. But from your statement above it seems you still have the `#` in front of the line. So the parser skips it.
Double check that you don't have it. Closing the issue. Please reopen if needed.
