### ISSUE TITLE
Desktop computer (minimum 6th Gen i7 or similar) with 10GigE NIC

### ISSUE THREAD

**Issue by joaogro** [srsran/srsRAN#760]
Hello there,

I'm testing the new release with the 5G NSA implementation on a X300 SDR, using a Desktop computer with i5 and 1GigE NIC. My question is very simple, it is mandatory to use a 10GigE NIC? Thank you in advance for the help.

**Comment by andrepuschmann** [comment]
Hey, we currently support only 10 MHz configs for both LTE+NR. With a X300 you can use 11.52 Msps. That leads to a raw data rate of `2 * 11.52e6 * 8 B (per complex sample) = 184.32 Mbyte/s = 1,474 GBit/s`. So yes, you need 10GigE for NSA. Also the i5 might be too weak, depending on the generation and clock speed of course.
