### ISSUE TITLE
libzmq not found

### ISSUE THREAD

**Issue by jas-** [srsran/srsRAN#768]
## Issue Description ##
ZeroMQ shared libraries not found when using [manual](https://docs.srslte.com/en/latest/app_notes/source/zeromq/source/index.html) if srsRAN previously built.

```
runtime library [libzmq.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib
```

## Setup Details ##
When srsRAN is "rebuilt" to use the ZeroMQ functionality in accordance with provided [documentation](https://docs.srslte.com/en/latest/app_notes/source/zeromq/source/index.html) the "build" folder must first be completely removed. Any attempt to recompile would not find the libmq shared object(s).

## Expected Behavior ##
ZeroMQ (libzmq*.so) files to be found on rebuilds

**Comment by andrepuschmann** [comment]
What's the issue here with srsRAN? This is just how CMake caches it's states.
