### ISSUE TITLE
AVP QOS not appearing in 4g attachment with open5gs

### ISSUE THREAD

**Issue by ayoub-tl** [srsran/srsRAN#801]
AVP QOS not appearing in 4g attachment with open5gs
Expected
![image](https://user-images.githubusercontent.com/68382823/152812363-f6a1f300-8ce3-47b7-92c9-6966c3a5bb21.png)
captured 
![image](https://user-images.githubusercontent.com/68382823/152812538-0ddfd05a-5991-4403-ba87-9c5ede308096.png)

**Comment by andrepuschmann** [comment]
Thanks for the report. Can you please share full logs/PCAPs for that?

**Comment by ayoub-tl** [comment]
after much investigation , turn out it was problem from open5gs  side, thanks for the fast response
