### ISSUE TITLE
srsUE (X310) not able to connect to 5G NSA srsENB (X310)

### ISSUE THREAD

**Issue by bondadakumarsai** [srsran/srsRAN#832]
## Issue Description ##
[Describe the issue in detail]
The srsUE is failing to attach to srsENB (5G NSA)

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

UHD 3.15 installed on both machines
Machine-1:
Ubuntu 18.04
Running srsEPC (NSA, version 21.10) and srsENB (NSA, version 21.10) with RF frontend as x310

Machine-2:
Ubuntu 18.04
Running srsUE (NSA version 21.10) with RF frontend as x310

## Expected Behavior ##
[What you expect to happen]

srsUE attachs to srsENB

## Actual Behaviour ##
[What happens instead e.g. error message]

From the console, I see these message printing on console repeatedly

Error receiving samples
Error calling srsran_ue_sync_work()
Error searching cell

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

[enb config file](https://drive.google.com/uc?export=download&id=14ApfaAlRupTzaqHvotRtTjt13lA4jwYw)
[rr config file ](https://drive.google.com/uc?export=download&id=1PoYt27en8fc_te2w22Un12LrphVm4amh)
[ue config file](https://drive.google.com/uc?export=download&id=1Xyn265Djd4-JbpN6-shmlbLr-wSuS-MK)

[ue log](https://drive.google.com/uc?export=download&id=1-fuFeTYXf8OpyVVBHRQm9HFOItuh6iQP)
[enb log](https://drive.google.com/uc?id=1SSOLBjUjxmvLv42a7wQKwdzHOuxQarEC&export=download)

 [enb console](https://drive.google.com/uc?export=download&id=1xJLOsORpLIDNBJl9fLn-65zQjlg4Y-fM)
 [ue console](https://drive.google.com/uc?export=download&id=1UmYxuuQNj2l-D-rHjdTnbYSLhV2_M26E)

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
You have to increase the MTU of the network interface towards the X310 9000. See logs that show default size of 1500 is used ("maximum frame size 1472 bytes").
