### ISSUE TITLE
Quick question on Raspberry Setup

### ISSUE THREAD

**Issue by mianrazo** [srsran/srsRAN#844]
Hi everyone, I was able to make to work the SRSEPC and SRSENB with B210, but I can't make it to go further than 15prb, I just want to confirm if this is expected due to the resources of the RPi, I have both EPC and ENB running on the same RPi, I've been trying to get a few more to try out a cluster setting but right now they are really expensive, also , I'm having a really hard time trying to make it to work in any other band than 3 on LTE, is there some setting I could be missing? thank you guys !

**Comment by andrepuschmann** [comment]
15 PRB is the max you can get out of the Pi4 without further tuning. So what you get is totally expected.
