### ISSUE TITLE
Problem Connecting UE with Preprogrammed Sim Card to the SRSRAN Network 

### ISSUE THREAD

**Issue by abgafoor469** [srsran/srsRAN#846]
Hi there!
I am facing the problem while connecting to the network, as I have installed SRSRAN on Linux based system with Blade-rf x115 as an Rf-frontend and have successfully started the EPC and connected the ENB with the EPC, Now I want to connect my mobile with network as explained in COTs-UE documentation but the problem is I have Pre-programmed sim card due to which I am not able to extract the key value, So is there any way that I can connect it to the network by extracting key from it or through IMSI or ICCID, please guide...
Regards

**Comment by andrepuschmann** [comment]
That doesn't work. You need cards with known credentials.
