### ISSUE TITLE
5G Section in RB configuration

### ISSUE THREAD

**Issue by matan1008** [srsran/srsRAN#857]
Hey!
I tried running a 4G setup with the new release and the ENB fails due to a `five_qi_config` error.
Is it obligatory to configure the `five_qi_config` in the RB configuration file?
If it is, could you please refer me to a documentation about its fields?
Thanks a lot!

**Comment by andrepuschmann** [comment]
Hey,
yes, the 5QI config is mandatory now because the the same binary for 4G/5G uses the same config parser. You can find an example config [here](https://github.com/srsran/srsRAN/blob/f2dff0b7a03e065060b48ea0a3c7a6a7890dfd46/srsenb/rb.conf.example#L98).

Closing the issue.
