### ISSUE TITLE
After Installing srsRAN with ZMQ and run ''make test''

### ISSUE THREAD

**Issue by Avatarrunt** [srsran/srsRAN#878]
## Issue Description ##
The following tests FAILED:
	 40 - viterbi_1000_0 (Failed)
	255 - pdcch_test-n100-p1-f1-Sauto-R1 (Failed)
	256 - pdcch_test-n100-p1-f1-S15-R1 (Failed)
	258 - pdcch_test-n100-p1-f2-Sauto-R1 (Failed)
	259 - pdcch_test-n100-p1-f2-S15-R1 (Failed)
	261 - pdcch_test-n100-p1-f3-Sauto-R1 (Failed)
	262 - pdcch_test-n100-p1-f3-S15-R1 (Failed)
	264 - pdcch_test-n100-p2-f1-Sauto-R1 (Failed)
	265 - pdcch_test-n100-p2-f1-S15-R1 (Failed)
	267 - pdcch_test-n100-p2-f2-Sauto-R1 (Failed)
	268 - pdcch_test-n100-p2-f2-S15-R1 (Failed)
	270 - pdcch_test-n100-p2-f3-Sauto-R1 (Failed)
	271 - pdcch_test-n100-p2-f3-S15-R1 (Failed)
	876 - benchmark_radio_multi_rf (Failed)
Errors while running CTest
Output from these tests are in: /home/runt/srsRAN/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:91: test] Error 8

pls help
[CMakeOutput.log](https://github.com/srsran/srsRAN/files/8803373/CMakeOutput.log)

**Comment by andrepuschmann** [comment]
What's the environment? OS, CPU, flag? I see it's gcc 11.2 but that's all we have. Please follow the instructions for posting issues.
