### ISSUE TITLE
5G SA  COST UE Error: Invalid configuration - No cell specified in rr.conf.

### ISSUE THREAD

**Issue by coolcoollly** [srsran/srsRAN#879]
## Issue Description ##
run srsenb with the tourial(https://docs.srsran.com/en/latest/app_notes/source/5g_sa_COTS/source/index.html).
I modify the config of enb.conf, rr.conf. But when I run srsenb, error comes out:
Error: Invalid configuration - No cell specified in rr.conf.
Error deriving EUTRA cell parameters
Error processing arguments.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
ubuntu 18.04; srsran 22.04; uhd 3.15; usrp X310

## Expected Behavior ##
 when I run srsenb,  there will generate a SA gnb.

## Actual Behaviour ##
I modify the config of enb.conf, rr.conf. But when I run srsenb, error comes out:
Error: Invalid configuration - No cell specified in rr.conf.
Error deriving EUTRA cell parameters
Error processing arguments.

## Steps to reproduce the problem ##
[srsran_conf.zip](https://github.com/srsran/srsRAN/files/8805400/srsran_conf.zip)

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

![2022-05-31 21-13-46 的屏幕截图](https://user-images.githubusercontent.com/84620893/171181824-8a5ef963-c30c-4bfa-ba33-e47ed83062cc.png)

**Comment by andrepuschmann** [comment]
It's not picking up your custom `rr.conf` correctly.

**Comment by coolcoollly** [comment]
thanks, I find I have not change srs21.10 to 22.04.

**Comment by mariatsampazi** [comment]
As mentioned above, a fix to this is to download the upgraded srsRAN version (as of today 22.04).

**Comment by loktiing** [comment]
> thanks, I find I have not change srs21.10 to 22.04.

Hi, I have changed srs21.10 to 22.04 by installing from source, but still get some error when I ran srsenb.

Error section five_qi_config not found.
Error parsing RB configuration
Error processing arguments.

Do you have the issue?

**Comment by andrepuschmann** [comment]
> Error section five_qi_config not found.

Use the updated `rb.conf.example` file

**Comment by loktiing** [comment]
Thank you! it works after I copied rb.conf.example to /root/.config/srsran/rb.conf.
