### ISSUE TITLE
ZeroMQ guide error

### ISSUE THREAD

**Issue by beruysaliz** [srsran/srsRAN#895]
## Issue Description ##
I am new with srsRAN and trying to learn. Basically following the LTE setup guide in srsRAN doc and I am taking such an error. 
![Screenshot_1](https://user-images.githubusercontent.com/19360447/174169568-637b96da-8e75-4d79-b0fc-989b33f77b7a.png)

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions
I use Ubuntu 18.04.5

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
Update your configs to the newest version

**Comment by beruysaliz** [comment]
how can I update the configs?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
