### ISSUE TITLE
SRS RAN 5G SA with bladerf 2.0

### ISSUE THREAD

**Issue by Dastgsm** [srsran/srsRAN#896]
I would like to ask if the SRAS RAN 5G SA could be used with bladerf 2.0 ?

Chears,

**Comment by andrepuschmann** [comment]
Yes, that's working.

**Comment by Dastgsm** [comment]
my computer is lenovo IP3 gaming with core i5 11300H with 8Giga of RAM. Is it on requirement of SRS-RAN 5G or not ?
