### ISSUE TITLE
Config Update

### ISSUE THREAD

**Issue by beruysaliz** [srsran/srsRAN#897]
## Issue Description ##
how can I update configs to the newest version? 

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by alvasMan** [comment]
Have you tried doing:
```
srsran_install_configs.sh <service/user> --force-no-db
```
?

This should override your configs to the newest version, while keeping your `user_db.csv` intact.

**Comment by sshawargullkhan75-lab** [comment]
https://github.com/srsran/srsRAN_4G/issues/897

**Comment by sshawargullkhan75-lab** [comment]
srsran_install_configs.sh <service/user> --force-no-db
