### ISSUE TITLE
Using USRP and srsRAN to build 4G base station configuration and connection problems

### ISSUE THREAD

**Issue by SpongeBobaa** [srsran/srsRAN#899]
Hello everyone, I want to try to use my mobile phone to connect to the 4G base station established by srsRAN, but I am currently encountering some problems and want to ask.

I am using the epc.conf.example and enb.conf.example files that come with srsRAN to test the base station signal. But it seems to have some problems connecting, it keeps saying
[INFO] [UHD RF]Tx while waiting for EOB, timed out... 9.82398 >= 7.43586. Starting new burst...
[INFO] [UHD RF]Tx while waiting for EOB, timed out... 17.0041 >= 15.4138. Starting new burst...
[INFO] [UHD RF]Tx while waiting for EOB, timed out... 36.6851 >= 36.6851. Starting new burst...

How should I modify and adjust it to work properly?

Second, I don't understand the file user_db_csv. Where should the content come from?

Thank you for your help

**Comment by robertfalkenberg** [comment]
Please have a look into our user manuals: https://docs.srsran.com/en/latest/usermanuals/source/srsepc/source/2_epc_getstarted.html?highlight=user_db
