### ISSUE TITLE
Error setting net.core.rmem_max in docker

### ISSUE THREAD

**Issue by shuimoshusheng** [srsran/srsRAN#909]
my container used ubuntu focal，usrp is x310.
 when i run sysctl -w net.core.rmem_max=2426666，return sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory

**Comment by andrepuschmann** [comment]
Very unrelated to srsRAN. But the issue is that those entries in proc cannot be manipulated from within the container. Modify them in the host.
