### ISSUE TITLE
NSA

### ISSUE THREAD

**Issue by JuanEstrada001** [srsran/srsRAN#922]
## Issue Description ##
I am having some problems implementing the NSA 5G cots with a N310. The UE is not being attached by the network and there are synchronization issues. The NSA COTs APP NOTE use a X300 but at the end of the APPNOTE tells that we can use a N310. Could you tell me if  we need 10Gbit ethernet interfaces with N310 as in the 5G NSA srsUE X300 appnote? Can this be the cause of the synchronization issues?

**Comment by andrepuschmann** [comment]
it should work with the N310 as well. There are device args that you  need to specify on the N310 to select the right output channels.

**Comment by brendan-mcauliffe** [comment]
Closing this issue. For further support with non-code issues, I suggest you use the [mailing list](https://lists.srsran.com/mailman/listinfo/srsran-users).
