### ISSUE TITLE
turn ON USE_LTE_RATES options UE fail to discover srsran eNodeB 

### ISSUE THREAD

**Issue by samssm** [srsran/srsRAN#939]
## Issue Description ##
[Describe the issue in detail]

turn ON USE_LTE_RATES options UE(iphone6 plus & iphone13 pro & Mi 10) fail to discover srsran eNodeB(although measure look fine in Keysight N9020A MXA Signal Analyzer), but UE(iphone6 plus & iphone13 pro & Mi 10) work fine when turn OFF USE_LTE_RATES in CMakefilelist。Anynone give a clue?

PS: 
1) Use ettus B210, default 23.04Msps have change to 30.72Msps in lib/src/phy/rf/rf_uhd_impl.c. 
2) all test case is 5MHz SISO, srsran tag is 19.12

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by samssm** [comment]
PS: all test case is 5MHz SISO

**Comment by samssm** [comment]
adj tx_adv_auto nsamples, this issue can be fixed, close this issue.

**Comment by samssm** [comment]
adj tx_adv_auto nsamples, this issue can be fixed, close this issue.

**Comment by andrepuschmann** [comment]
Excellent. Thanks for the feedback
