### ISSUE TITLE
UE cannot find LTE network

### ISSUE THREAD

**Issue by 08050736** [srsran/srsRAN#941]
**Issue Description**
> 
when I run sudo srsepc and sudo srsenb, the corresponding network cannot be found using UE. I modified MCC and MNC and dl_earfn but still can't find it.

** Setup **
> 
Ubuntu18.04
USRP B210
smart phone: Samsung A31 and iPhone 8 Plus

**Run srsepc and srsenb **
![image](https://user-images.githubusercontent.com/95597624/180781704-c29c3f6f-6afb-4592-b7f0-408644d6c05d.jpeg)

![image](https://user-images.githubusercontent.com/95597624/180781760-3d9bb7a8-cf98-4e6c-b030-3cc26ca5a91d.jpeg)

**Comment by LongRiver-hash** [comment]
Is SIM information in your config file user_db.csv?

**Comment by brendan-mcauliffe** [comment]
Hi, this looks more like an issue for the mailing list. You can subscribe to the list [here](https://lists.srsran.com/mailman/listinfo/srsran-users). 

I suggest you send an email outlining your set-up as you did above, and attach the configs and logs for srsENB & srsEPC. 

You may also want to have a look at [this app note](https://docs.srsran.com/en/latest/app_notes/source/cots_ue/source/index.html) if you have not done so already. 

Closing this issue.
