### ISSUE TITLE
Is Tracking Area Update Request generating by UE in current code?

### ISSUE THREAD

**Issue by zzylol** [srsran/srsRAN#944]
Dear Author,

I am wondering in current implementation, whether UE in LTE will generate TAU request messages, since I find this part is in TODO: https://github.com/srsran/srsRAN/blob/master/lib/include/srsran/asn1/liblte_mme.h#L3191

I am looking forward to your answer. 

Thanks!

**Comment by andrepuschmann** [comment]
Dear @zzylol,
TAU aren't supported in srsRAN I am afraid. That being said, using a COTS phone and a third-party core with TAU support, the eNB will of course happily forward the messages.
Thanks
