### ISSUE TITLE
Developer guide 

### ISSUE THREAD

**Issue by kbaccar** [srsran/srsRAN#967]
# Issue Description
Hello, im currently sturggling with some modifications on srsran. I would like to know if there is any developer guide or a doc for the library.

Thanks

**Comment by brendan-mcauliffe** [comment]
Hi, we do not have a Dev Guide for srsRAN. I suggest you post your problem to the [mailing list](https://lists.srsran.com/mailman/listinfo/srsran-users), this is the best way to get help on modifying the code base. 

Closing this issue.
