### ISSUE TITLE
SCTP abort message [S1AP failed to initiate] using open5gs and srsRAN

### ISSUE THREAD

**Issue by Citrayaf** [srsran/srsRAN#968]
## Issue Description ##
I tried to use srsRAN and open5gs for 5G NSA simulation for UE and eNodeB I use srsRAN and for EPC I use open5gs in different VM. when I try to integrate these, from eNb to open5gs always send SCTP abort message if I trace using wireshark. I don't know what is the main problem come from srsRAN or open5gs. 

## Setup Details ##
I use virtual ZeroMQ, epc uses open5gs, for 5G NSA simulation, in different VM
10.14.2.5 is IP for open5gs
10.14.2.7 is IP for srsRAN

## Expected Behavior ##
S1AP procedure is OK

## Actual Behaviour ##
when I try to integrate these, from eNb to open5gs always send SCTP abort message if I trace using wireshark. in enb.log shows that S1AP failed to initiate.
open5Gs
![image](https://user-images.githubusercontent.com/71243914/186060920-c2c05584-d804-441e-8787-10897b788a0a.png)
srsRAN
![image](https://user-images.githubusercontent.com/71243914/186060980-f061ae01-6d83-4b0e-bf70-9f454af8d51a.png)
## Steps to reproduce the problem ##
uses different VM, epc uses open5gs
## Additional Information ##
I have attached all trace files:
srsRAN 
[enb.log](https://github.com/open5gs/open5gs/files/9399024/enb.log)
[srsRAN_trace.zip](https://github.com/open5gs/open5gs/files/9399028/srsRAN_trace.zip)
open5gs
[open5G_trace.zip](https://github.com/open5gs/open5gs/files/9399029/open5G_trace.zip)

**Comment by Citrayaf** [comment]
I have fixed the problems, I misconfigured in srsRAN enb side IP configuration after I change it to the correct one all is working fine. 
Thanks you

**Comment by yopie176** [comment]
can you share config amf.yaml, upf.yaml, srsenb/enb.conf and srsenb/rr.conf
thanks

**Comment by Citrayaf** [comment]
Sorry for my late reply, sorry right now I can share it to those files to you because I have lot work to do. But you can access my repo in this link https://github.com/Citrayaf/How-to-build-OpenCore-and-OpenRAN-for-5G . I have made documentation about what I have done to build this system, Maybe you can check. 
Thanks very much. Later I will send you those files..
