### ISSUE TITLE
5G SA on N48 (CBRS/TDD) possible?

### ISSUE THREAD

**Issue by mianrazo** [srsran/srsRAN#969]
## Issue Description ##
Hi, sorry for taking out your time guys, just want to confirm if it's possible to configure band N48 (5GSA) on enodeB, I've read everywhere that enodeB supports only FDD, but looks like on NSA its possible to add TDD bands on top of FDD, is that correct? I'm looking forward to test only N48 (CBRS TDD) on USRP B210, any help or guidance would be greatly appreciated, thanks!
 

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
USRP B210 with SRS EPC on Ubuntu 18.04 trying to configure a TDD band for CBRS testing B48

## Expected Behavior ##
USRP B210 to transmit on specified earfcn

## Actual Behaviour ##
USRP B210 not transmitting, failing at start on B48 setttings 

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by robertfalkenberg** [comment]
Currently for 5G-SA, TDD bands with 30kHz SCS (e.g. n78, n77, n48) are not supported.
