### ISSUE TITLE
Is it possible to connect  LimeSDR (UE) to the LimeSDR (ENB)?

### ISSUE THREAD

**Issue by egortaran** [srsran/srsRAN#972]
## Issue Description ##
Hello dear developers and users of srsRAN. I want use LimeSDR like UE. I will describe it with the example

## Setup Details ##
- 2 computers with Ubuntu 20.04
- 2 limeSDR v1.4
- open5gs
- srsRAN 22.04

## Expected Behavior ##
I would like to use the first computer and LimeSDR as ENB. And the second computer and LimeSDR as a UE

## Additional Information ##
I have the following questions:
1. Is it possible to connect the second LimeSDR (UE) to the first LimeSDR (ENB)?
2. Is it possible to call using Asterisk from the first computer to the second?

I will be glad to hear any answer answer, or links to documentation and which section. I used the following documentation. I admit that I may miss something:
- https://docs.srsran.com/en/latest/getting_started.html
- https://docs.srsran.com/en/latest/usermanuals/source/srsue/source/1_ue_intro.html#ue-intro

**Comment by jtang613** [comment]
1. I've tested extensively with LTE Bands 1 and 4 on LimeSDR. LTE works well with LimeSDR + SRSRAN + Open5gs. 
I've not yet been able to get 5G to connect with either SRSUE or with COTS UEs (OnePlus 9 5G, Quectel RM500). The most activity I've been able to see on the gNB is the RRC/RLC SetupRequests coming in, but nothing after. I've not entirely ruled out user-error though, so ymmv.

2. Making voice calls will require either VoIP, VoLTE or CSFB.
Try this link to get VoIP and then VoLTE working: https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup.
For CSFB, you'll need another SDR running a 2G/3G stack like OSMOCOM. nickvsnetworking has a good tutorial here: https://nickvsnetworking.com/osmomsc-and-open5gs-mme-sgs-interface-for-cscf-interran-handover/

**Comment by egortaran** [comment]
Dear [jtang613](https://github.com/jtang613). Thank you very much for the answer. Yes, I agree with you that VoLTE works well with LimeSDR + SRSRAN + Open5gs.
I don't want to run with a 5G core, it's enough for me to connect LimeSDR (UE) to Lime SDR (ENB), and find out if it's possible to do this.
If possible, I would like to connect a softphone using Asterisks

**Comment by egortaran** [comment]
Yes. Is it possible
