### ISSUE TITLE
N3 is missing GTP-U PDU session container extension header

### ISSUE THREAD

**Issue by mk122112** [srsran/srsRAN#976]
## Issue Description ##

N3 is missing GTP-U PDU session container extension header.
It looks more like an S1-U interface.

## Setup Details ##

srsENB, srsUE and Core in separate VMs.

srsran release 22.04.1

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by mk122112** [comment]
![From_CN_with_PDU_Session_container](https://user-images.githubusercontent.com/112568203/187857684-4e949342-2b37-44c0-b7fa-1003674fb92c.JPG)
![From_srsenb_without_PDU_Session_container](https://user-images.githubusercontent.com/112568203/187857697-ae4e5c69-2abc-4cd4-866b-830e8f8b10a5.JPG)

**Comment by andrepuschmann** [comment]
@mk122112 Thanks for reporting this. I confirm that we don't pack the PDU session container. We simply didn't need it for our purposes. There are currently also no plans to add it anytime soon. That being said, PRs are of course open. Closing this.

**Comment by mk122112** [comment]
I was using srsRAN with a different 5GC and user plane is not working due to this. But I don't need it right now.

**Comment by andrepuschmann** [comment]
> I was using srsRAN with a different 5GC and user plane is not working due to this. But I don't need it right now.

Ah, interesting. We assumed it wasn't mandatory. Can you disclose the particular 5GC you've used for this?

**Comment by mk122112** [comment]
It's simulated 5GC developed by Ericsson for test.
