### ISSUE TITLE
can anyone help me in implemenating srsRAN on Raspberry pi 4

### ISSUE THREAD

**Issue by anum63** [srsran/srsRAN#982]
## Issue Description ##
[Describe the issue in detail]

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by TallGuy74** [comment]
@anum63 I have a 4G UE/eNB running on Odroid N2+ hardware using USRP X300's connected to the internal ethernet controller. You can probably get this setup working on the Raspberry Pi 4 as well, but it's possible the CPU can't be run fast enough. You WILL need to overclock the CPU to at least 2 GHz.

**Comment by robertfalkenberg** [comment]
Please have a look here: https://docs.srsran.com/en/latest/app_notes/source/pi4/source/index.html

**Comment by andrepuschmann** [comment]
I am closing the issue. Sufficient information has been provided in the appnote and this ticket. Please reopen should more specific questions arise.
