### ISSUE TITLE
srslte ppa jammy Release Err: 404  Not Found [IP: 185.125.190.52 443]

### ISSUE THREAD

**Issue by safari-srslte** [srsran/srsRAN#994]
Hi,
I want to ran the srsRAN system on my laptop. Previously  I did it many times and it was working OK. I'm using ZMQ to connect enb and ue. Recently i upgraded my system to Ubuntu 22.04 jammy and now its not working, the srsenb gives error. when I update the system i got following error .

1. sudo apt-get update#
Err:8 https://ppa.launchpadcontent.net/srslte/releases/ubuntu jammy Release 404  Not Found [IP: 185.125.190.52 443]
(i go to this link and there is no jammy release, but how is it possible that srsRAN is available  for 22.04 and srslte launchpad didn't?)

2. The output of srsenb is given below,

root@safarifone-HP-ProBook-450-G7:/usr/src/srsRAN/build# ./srsenb/src/srsenb --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6"
Active RF plugins: libsrsran_rf_soapy.so libsrsran_rf_blade.so libsrsran_rf_zmq.so
Inactive RF plugins: 
---  Software Radio Systems LTE eNodeB  ---

Couldn't open , trying /root/.config/srsran/enb.conf
Reading configuration file /root/.config/srsran/enb.conf...
Couldn't open sib.conf, trying /root/.config/srsran/sib.conf
Couldn't open rr.conf, trying /root/.config/srsran/rr.conf
Couldn't open rb.conf, trying /root/.config/srsran/rb.conf

Built in Release mode using commit f2dff0b7a on branch master.

Error section five_qi_config not found.
Error parsing RB configuration
Error processing arguments.

**Comment by andrepuschmann** [comment]
Please update the config files. You seem to be using old ones, i.e. from previous releases.
