### ISSUE TITLE
SA srsUE : Tx while waiting for EOB, timed out  --------  [PHY_LIB] [I] [ 0] Discarded PDCCH candidate L=2;ncce=4; Correlation is too low (0.0<0.5); EPRE=-34.79; RSRP=-50.25;

### ISSUE THREAD

**Issue by fengchao-1998** [srsran/srsRAN#995]
## Issue Description ##
Out of sync occurs after SA srsue completes cell search proc.

2022-09-23T02:18:46.085754 [PHY_LIB] [D] [    0]  PBCH-NR Rx: crc=KO
2022-09-23T02:18:46.085754 [PHY1-NR] [W] [ 4120] PBCH-MIB: CRC failed
2022-09-23T02:18:46.063812 [PHY_LIB] [I] [    0]  PDCCH DMRS Rx: Measure L=2; ncce=4; RSRP=-50.2 dBfs; EPRE=-34.8 dBfs; Corr=0.028
2022-09-23T02:18:46.063813 [PHY_LIB] [I] [    0]  Discarded PDCCH candidate L=2;ncce=4; Correlation is too low (0.0<0.5); EPRE=-34.79; RSRP=-50.25;
2022-09-23T02:18:46.063814 [PHY_LIB] [I] [    0]  PDCCH DMRS Rx: Measure L=2; ncce=4; RSRP=-50.2 dBfs; EPRE=-34.8 dBfs; Corr=0.028
2022-09-23T02:18:46.063815 [PHY_LIB] [I] [    0]  Discarded PDCCH candidate L=2;ncce=4; Correlation is too low (0.0<0.5); EPRE=-34.79; RSRP=-50.25;

## Setup Details ##
PC： Lenovo ThinkPad X13 G2(11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz*4、16G)

OS：ubuntu20.04       5.14.0-1051-oem #58-Ubuntu SMP Fri Aug 26 05:50:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

UHD：3.15    
USRP B210

srsRAN：22.04.1

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
Inactive RF plugins:
Couldn't open , trying /root/.config/srsran/ue.conf
Reading configuration file /root/.config/srsran/ue.conf...

Built in RelWithDebInfo mode using 22.04.1.

Opening 1 channels in RF device=default with args=default
Supported RF device list: UHD zmq file
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_3.15.0.0-0-unknown
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test...
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test...
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz...
[INFO] [B200] Actually got clock rate 23.040000 MHz.
RF device 'UHD' successfully opened
Waiting PHY to initialize ... done!
Attaching UE...
RF status: O=0, U=2, L=0
[INFO] [UHD RF] Tx while waiting for EOB, timed out... 3.74514 >= 3.17509. Starting new burst...
RF status: O=0, U=1, L=0
[INFO] [UHD RF] Tx while waiting for EOB, timed out... 5.92439 >= 5.75514. Starting new burst...
RF status: O=0, U=1, L=0
Stopping ..
Saving NAS PCAP file (DLT=148) to /tmp/ue_nas.pcap

> 

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##

[ue_nas.txt](https://github.com/srsran/srsRAN/files/9606035/ue_nas.txt)
[ue.txt](https://github.com/srsran/srsRAN/files/9606038/ue.txt)

**Comment by andrepuschmann** [comment]
Make sure you've set the CPU to performance governor to avoid the underruns. The PBCH code is a bit resource so you wanna make sure to have enough horse power to do it in realtime. Also make sure the signal quality is good. I am closing the issue. Please reopen if it still doesn't work for you. Thanks
