### ISSUE TITLE
RuntimeError: Multiple sampling rates upstream of RX Terminator 0

### ISSUE THREAD

**Issue by beruysaliz** [srsran/srsRAN#999]
## Issue Description ##
[Describe the issue in detail]
when I set number of channels to 2 in enb.conf file.
![Screenshot from 2022-09-22 12-26-21](https://user-images.githubusercontent.com/19360447/191725356-19b0accb-21f5-42d9-9eb9-d3034310be18.png)

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions
Linux 18.05, UHD 3.15, USRP N321
[enb.txt](https://github.com/srsran/srsRAN/files/9624826/enb.txt)

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]
in enb.conf file set tm=4 and nof_ports=2 and execute sudo srsenb in terminal.
## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
Please use the search function and read the appnotes. The question has been addressed a few times already. Closing it.
